name: Run tests and upload coverage

on: 
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker build -t polygondust -f ./Dockerfile.coverage .
          
      - name: Create coverage_build directory
        run: |
          mkdir coverage_build
      
      - name: Run Test
        run: |
          docker run -v ./coverage_build/:/polygondust/coverage_build polygondust sh scripts/coverage.sh xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./coverage_build/polygondust-coverage-xml.xml
          token: ${{ secrets.CODECOV_TOKEN }}